### ISSUE TITLE
how do i make vhosts accessible externally?

### ISSUE THREAD

**Issue by mmjturner** [tatanus/SPF#14]
Vhosts activate fine, but aren't accessible externally...
what do i change? hosts?

**Comment by tatanus** [comment]
vhosts should automatically be accessible externally, assuming that : 
1) your host/ip is accessible from the internet
2) you have a wildcard DNS entry for your custom domain pointing to your IP
3) you do not have a firewall or other software/device preventing access
4) you have changed the config file to use/allow vhosts

**Comment by mmjturner** [comment]
Yeah, i didn't realize the ports were different rules. I added a new inbound rule on my firewall.
It worked for few days, but now i get this:
└──╼ #python web.py default.cgf
Traceback (most recent call last):
  File "web.py", line 298, in <module>
    PhishingWebServer(Utils.decompressDict(sys.argv[1])).start()
  File "/opt/SPF/spf/core/utils.py", line 25, in decompressDict
    return json.loads(zlib.decompress(base64.b64decode(s)))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

I haven't touched anything else?

**Comment by mmjturner** [comment]
Also reinstalled SPF. Still same? What happened?
