### ISSUE TITLE
More detail on arguments?

### ISSUE THREAD

**Issue by mmjturner** [tatanus/SPF#15]
Possible to get a little more explanation on the usage of these arguments:
-d <domain>          domain name to phish
  -c <company's name>  name of company to phish
  --ip <IP address>    IP of webserver defaults to [192.168.1.124]
  -v, --verbosity      increase output verbosity?

Thanks

**Comment by tatanus** [comment]
what is the confusion.  the description provide should fairly accurately describe what they do.   for example, the -v option increases the verbosity of the output and the --ip can be used to specify the ip address of the webserver, which in your case appears to default to 192.168.1.124.

Can you please let me know where the confusion is?

**Comment by tatanus** [comment]
this issue has not had any comment on it in a couple of months, thus I am closing it out
