### ISSUE TITLE
New Template: DWA

### ISSUE THREAD

**Issue by LAzyFrAAnk** [tatanus/SPF#17]
would you add the new template of DWA? it' would be great

![image](https://cloud.githubusercontent.com/assets/27416170/25967311/498b0ab4-36c0-11e7-98c6-0ff1d656cb7e.png)

**Comment by tatanus** [comment]
I do not have immediate access to a DWA install, thus successfully cloning and setting up a template is not trivial.  If you happen to have access to one and want to create the template and share it, that would be awesome.  Otherwise I will add it to the list of things to do.

**Comment by LAzyFrAAnk** [comment]
Sure, I can share domino 8.5 and 9.x client to u too

**Comment by LAzyFrAAnk** [comment]
How can i share that to u ?

**Comment by tatanus** [comment]
do you have the template created or are you trying to share your install of SWA with me?

If you have the template, simply do a pull request.

If you have a install of DWA to share with me, it will have to wait as I am leaving the country on a business trip in about 12 hours.

**Comment by tatanus** [comment]
never mind.  I found a copy of DWA and went ahead and made a web and email template for it.   it is labeled "domino".    you can find the template at:   https://github.com/tatanus/SPF/tree/master/spf/templates/web/domino

**Comment by tatanus** [comment]
that should work for you.  please let me know if you have any issues.
