### ISSUE TITLE
Choosing template - 2nd run

### ISSUE THREAD

**Issue by Raytri3** [tatanus/SPF#2]
Sorry for starting new thread but this is an issue with the newest code base - more specifically the template choice. Here is the "issue":

1. Run spf and choose 1 template - send your email then end spf via ctrl+c
2. Re-run spf - the only choice you get is the one from 1. If you choose it no problem. If any other number is entered you get an error.
3. Re-run spf a second time - you get all choices back.

**Comment by tatanus** [comment]
corrected.  Now the template selection does bounds checking on the input.
