### ISSUE TITLE
Error Text read from config file - enhancement request

### ISSUE THREAD

**Issue by Raytri3** [tatanus/SPF#4]
Is it possible to get the error message to be read in from the config file? I do not like modifying the code every time I change the message (always afraid I am going to fat finger something).  I often use a different one depending on the audience. One of my current favorites is (trying to proactively prevent them from calling anyone): 

We're currently experiencing technical difficulties. IT is working closely with our external partners to make sure these issues get resolved as quickly as possible.
We'll update you when we've got more info to share.

**Comment by tatanus** [comment]
should be easy enough to do.   I can have it be a new entry in the config file.  you can either provide it with a string or an URL.   if it is an URL, it will simply redirect to that URL but if it is a string, then it will simply display that string in place of the current  ERROR page.

Does that sound reasonable?

**Comment by Raytri3** [comment]
sounds perfect.

**Comment by tatanus** [comment]
Done.  Now there are two additional values in the config file:
ERROR_URL
ERROR_TEXT

if these are left blank, then the default error page is used.
If an URL (with the http:// https://) is provided to the ERROR_URL then the user will be redirected to that url upon form submission.

if html text is entered into ERROR_TEXT then a new error page with that text will be displayed.
