### ISSUE TITLE
2 new bugs/issues +1 enhancement

### ISSUE THREAD

**Issue by Raytri3** [tatanus/SPF#5]
Bugs/Issues
1. I ran SPF with the -v option (for verbose) and noticed that in this "mode" I don't have the ability to select the template like I do in regular "mode".
2. The reports are written under  _example... I would like to see them written under the domain name - thought it did this but I have yet to get it to do so (could be me doing it wrong).

Enhancement
Ok this is a big one but I think it would be really cool in the long run. However do to the amount of changes, if it doesn't happen I completely understand. Since we have an option to read in an email file can we use that file to set other parameters/options? For example if I have a CSV file that looks like this: email,template#,pillageY/N  I could have a  lot more flexibility when sending emails. I could set who gets which template and whether or not they get pillaged by user rather than "all or nothing". Note I could accomplish this functionality through multiple runs but that negates the SPEED part :)

**Comment by tatanus** [comment]
1)
the -v option should not be restricting you from selecting the template.   What may be happening is a "feature" of the tool in that if:
- SPF was run against the same target domain and source domain in the past
- The resulting directory is still present
- You selected templates before
then that is all saved in the sqllite file.  try removing that file and see if it works then.
Or it could just be that I am mis understanding your issue.

2)
it should create the directory with the name of <domain_name>_<phishing_domiain>
By default, it uses the values from the config file:
PHISHING_DOMAIN: example.com
DOMAIN_NAME: example.com

where DOMAIN_NAME is the target domain and PHISHING_DOMAIN is the domain that you possibly registered to send emails from.

As for the enhancement, I will move it to a feature request, and I like the idea, but it may be a while before it is done.

**Comment by tatanus** [comment]
If it is still not working for you, please let me know and we can jump on chat/skype or something to try to figure out what is wrong.

**Comment by tatanus** [comment]
due to lack of response
