### ISSUE TITLE
External ip!

### ISSUE THREAD

**Issue by jteslaxxx** [tatanus/SPF#8]
Hello wanted to ask do you have any tips to change from internal ip to external! I mean pages use external ip or noip client! I tried it to configure, everything passes nicely, but pages refuse to open in browser! 
Thanks!

**Comment by tatanus** [comment]
have you tried the "--ip" commandline option?  If this does not work for you, please let me know.  Also, make sure you have the latest build/download.

**Comment by jteslaxxx** [comment]
I tried in default configuration change ip from 0.0.0 to my external ip so eventually use my DUC client!
Thanks for your answer I'm gonna try now use "--ip" command and gonna come back to you!

**Comment by jteslaxxx** [comment]
So tried to change in conf file and also tried "--ip" options, but still i,m not able to use external ip! Any suggestions?

**Comment by jteslaxxx** [comment]
Everything else seems to be fine, made even portforwarding, but still i,m only on local network!

**Comment by tatanus** [comment]
remove any target/sensitive information, but can you provide me with the commandline and the default.cfg file you are using so I can try to replicate?

**Comment by jteslaxxx** [comment]
[MISC]
PHISHING_DOMAIN: example.com
DOMAIN_NAME: example.com 
EMAILS_MAX: 100
EMAIL_DELAY: 1
DATABASE: spf.sqlite

[TEMPLATES]
WEB_TEMPLATE_PATH: templates/web/
EMAIL_TEMPLATE_PATH: templates/email/

[SMTP]
DETERMINE_SMTP: 1
USE_SPECIFIC_SMTP: 0
SMTP_SERVER: 1.1.1.1
SMTP_USER: XXXX
SMTP_PASS: XXXX
SMTP_FROMADDR: support@example.com
SMTP_DISPLAYNAME: SUPPORT
SMTP_PORT: 25

[EXTERNAL_TOOL_PATHS]
#THEHARVESTER_PATH: /usr/bin/theharvester
THEHARVESTER_PATH: /usr/share/theHarvester/theHarvester.py
BEEF_PATH: /usr/bin/beef-xss   (have also some misunderstood with beef module getting ip error)

[ADDITIONAL_ATTACKS]
ENABLE_KEYLOGGING: 1
ENABLE_BEEF: 0
ENABLE_USER_TRACKING: 1

[WEB]
IP: (here use for example either my external ip adress what are connected with noip)
ENABLE_HOST_BASED_VHOSTS: 0 (have tried this option enabled or disabled 0/1 option)
DEFAULT_WEB_PORT: 80
VHOST_PORT_MIN: 8000
VHOST_PORT_MAX: 9000
ERROR_URL: 
ERROR_TEXT: 

[EMAIL_FILE_ATTACHMENT]
ATTACHMENT_FULLPATH: 
ATTACHMENT_FILENAME:

**Comment by jteslaxxx** [comment]
For example
./spf.py --test -v --ip "extenal ip" -p target..com -d target.com 
this one of commands i have tried, but have tried any way

**Comment by tatanus** [comment]
if you run:     (replace 1.2.3.4 with your external ip)
./spf.py -v -y -w --ip 1.2.3.4

do you see lines such as (they will be near the end of the output):
[*] [VERBOSE] Started website [cisco_vpn ] on [http://1.2.3.4:8000]
[*] [VERBOSE] Started website [citrix2   ] on [http://1.2.3.4:8001]
[*] [VERBOSE] Started website [junipervpn] on [http://1.2.3.4:8002]
[*] [VERBOSE] Started website [owa       ] on [http://1.2.3.4:8003]
[*] [VERBOSE] Started website [office365 ] on [http://1.2.3.4:8004]
[*] [VERBOSE] Started website [citrix    ] on [http://1.2.3.4:8005]


if not, can you tell me what you do see?

**Comment by jteslaxxx** [comment]
Ssame thing and actually tried it before, i am getting answer unabe to connect, but when type my internal ip to search bar it working fine!

**Comment by jteslaxxx** [comment]
And yes i can see that spf is showing that server started on my external ip! But when opening in browser Iam getting error that unable to connect! 
Have tried several ways nothing

**Comment by tatanus** [comment]
okay.   just so I understand.  Your system has 2 interfaces, one internal and 1 external.   The --ip option is just there to specify which network interface to use.   The external ip is not for a network device (firewall, router, etc...) is it?  If it is, then just just your internal IP for SPF and then set up port forwarding on your network/external device.

I have not encountered this issue before.   I will have to see what I can find.

**Comment by jteslaxxx** [comment]
Closing up the issue, sorry everything just fine and working fine on external ip and noip also!
Problem was that I made default config but forget directory changing showing towards my templates in public directory! So everything because of little stupidity! 
Thanks for support awesome project, and gonna stay tuned up!
