### ISSUE TITLE
external ip and template usage!

### ISSUE THREAD

**Issue by jteslaxxx** [tatanus/SPF#9]
So hello again!
Still continue to have some errors in usage of my external ip!
So i tried like this i put templates to localhost/var/www/html folders to run them on localhost and my external ip!
i changed default.cnf so it points out WEB_TEMPLATE_PATH: /var/www/html/templates/
When i run spf i use --ip command all seems fine: VERBOSE] Found the following web sites: [templates/web/citrix2/CONFIG]
[*] [VERBOSE] Found the following web sites: [/var/www/html/templates/web/office365/CONFIG]
[*] [VERBOSE] Found the following web sites: [[/var/www/html/templates/web/cisco/CONFIG]
[*] [VERBOSE] Found the following web sites: [[/var/www/html/templates/web/juniper_vpn/CONFIG]
[*] [VERBOSE] Found the following web sites: [[/var/www/html/templates/web/owa/CONFIG]
[*] [VERBOSE] Found the following web sites: [/var/www/html/templates/web/citrix/CONFIG]
[*] [VERBOSE] Started website [cisco_vpn ] on [http://9x.156.0.0.0:8000]
[*] [VERBOSE] Started website [citrix2   ] on [http://9x.156.0.0.0:8001]
[*] [VERBOSE] Started website [junipervpn] on [http://9x.156.0.0:8002]
[*] [VERBOSE] Started website [owa       ] on [http://9x.1560.0.0.04:8003]
[*] [VERBOSE] Started website [office365 ] on [http://9x.156.0.0.0:8004]
[*] [VERBOSE] Started website [citrix    ] on [http://9x.1560.0.0:8005]
[*] [VERBOSE] Started WebServer with pid = [5867]

pages are even opening on my external ip, but keylogger is disabled, i cannot see in terminal any changes, and passwords are not captured! when i switch ip to my internal ip: 192.16X.X.XX1
pages are visible and working like should! Limitations is only local and spf idea is changed! 
could you please paste me some example of your test config files so i can look up what i,m doing wrong or where is cause!
Also problem with beef module! When i enable it in conf file get some ip error!
I,m running beef on my external ip and dynamic dns client and all works fine!

**Comment by tatanus** [comment]
I will look into your first issue you mentioned, but as for beef, it is not ready for use yet, it is simply a place holder for now.

**Comment by jteslaxxx** [comment]
ok i,m gonna try do work on it outself also and post if have some kind progress! In subject of external ip its strange! 
On first issue regarding i,m continue to try to  solveissue but in any way i try I,m able to use only internal ip!

**Comment by tatanus** [comment]
are you still experiencing the issue?

**Comment by tatanus** [comment]
As I have not heard back on this issue from you in 3 months I will close it out.
